# Generated by Django 4.1.7 on 2023-02-28 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True, verbose_name='видимость')),
                ('order', models.IntegerField(default=10, verbose_name='порядковый номер')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=20, verbose_name='название')),
                ('slug', models.SlugField(max_length=255, null=True, verbose_name='URL')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='Named URL')),
            ],
            options={
                'verbose_name': 'меню',
                'verbose_name_plural': 'меню',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_visible', models.BooleanField(default=True, verbose_name='видимость')),
                ('order', models.IntegerField(default=10, verbose_name='порядковый номер')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, verbose_name='пункт')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='ссылка')),
                ('named_url', models.CharField(blank=True, max_length=255, verbose_name='имя URL')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menu', verbose_name='меню')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menuitem', verbose_name='родитель')),
            ],
            options={
                'verbose_name': 'пункт меню',
                'verbose_name_plural': 'пункты меню',
                'ordering': ('order',),
            },
        ),
    ]
